# Configuration file for audit script.

discovery: nmap -sP -PE -iL targets.txt
port_scan: nmap -sSV -p 31337,80

notification_email: alton.jx@gmail.com

smtp_server: smtp.office365.com
smtp_username: alton@vonahi.com
smtp_password: WZ|/wJEIlUA,yo0@
smtp_port: 587